version: '3'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_PASSWORD=password

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"  #IMPORTANT
    environment:
      - DB_POSTGRESDB_HOST=postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_PASSWORD=password
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Sadzbx13*
      - WEBHOOK_URL=https://n8n-iril.onrender.com
    depends_on:
      - postgres
